DROP TABLE jugadores_creacion_goles_tiros;

CREATE TABLE `jugadores_creacion_goles_tiros` 
(
    `Rk`	VARCHAR(50),
    `Player`	VARCHAR(50),
    `Nation`	VARCHAR(50),
    `Pos`	VARCHAR(50),
    `Squad`	VARCHAR(50),
    `Age`	VARCHAR(50),
    `Born`	VARCHAR(50),
    `90s`	VARCHAR(50),
    `SCA`	VARCHAR(50),
    `SCA90`	VARCHAR(50),
    `PassLive`	VARCHAR(50),
    `PassDead`	VARCHAR(50),
    `TO`	VARCHAR(50),
    `Sh`	VARCHAR(50),
    `Fld`	VARCHAR(50),
    `Def`	VARCHAR(50),
    `GCA`	VARCHAR(50),
    `GCA90`	VARCHAR(50),
    `PassLive2`	VARCHAR(50),
    `PassDead2`	VARCHAR(50),
    `TO2`	VARCHAR(50),
    `Sh2`	VARCHAR(50),
    `Fld2`	VARCHAR(50),
    `Def2`	VARCHAR(50),
    PRIMARY KEY (Rk)
);

DROP TABLE jugadores_defensivo;
CREATE TABLE `jugadores_defensivo` 
(
    `Rk`	INT,
    `Player`	VARCHAR(512),
    `Nation`	VARCHAR(512),
    `Pos`	VARCHAR(512),
    `Squad`	VARCHAR(512),
    `Age`	VARCHAR(512),
    `Born`	INT,
    `90s`	DOUBLE,
    `Tkl`	INT,
    `TklW`	INT,
    `Def 3rd`	INT,
    `Mid 3rd`	INT,
    `Att 3rd`	VARCHAR(512),
    `Tkl2`	INT,
    `Att`	INT,
    `Tkl%`	DOUBLE,
    `Lost`	INT,
    `Blocks`	INT,
    `Sh`	VARCHAR(512),
    `Pass`	INT,
    `Int`	INT,
    `Tkl+Int`	INT,
    `Clr`	INT,
    `Err`	VARCHAR(512),
    PRIMARY KEY (Rk)
);

DROP TABLE jugadores_diversas;
CREATE TABLE `jugadores_diversas` 
(
    `Rk`	INT,
    `Player`	VARCHAR(512),
    `Nation`	VARCHAR(512),
    `Pos`	VARCHAR(512),
    `Squad`	VARCHAR(512),
    `Age`	VARCHAR(512),
    `Born`	INT,
    `90s`	DOUBLE,
    `CrdY`	INT,
    `CrdR`	VARCHAR(512),
    `2CrdY`	VARCHAR(512),
    `Fls`	INT,
    `Fld`	INT,
    `Off`	VARCHAR(512),
    `Crs`	VARCHAR(512),
    `Int`	INT,
    `TklW`	INT,
    `PKwon`	VARCHAR(512),
    `PKcon`	VARCHAR(512),
    `OG`	VARCHAR(512),
    `Recov`	INT,
    `Won`	INT,
    `Lost`	INT,
    `Won%`	DOUBLE,
    PRIMARY KEY (Rk)
);

DROP TABLE jugadores_generales;
CREATE TABLE `jugadores_generales` 
(
    `Rk`	INT,
    `Player`	VARCHAR(512),
    `Nation`	VARCHAR(512),
    `Pos`	VARCHAR(512),
    `Squad`	VARCHAR(512),
    `Age`	VARCHAR(512),
    `Born`	INT,
    `MP`	INT,
    `Starts`	INT,
    `Min`	INT,
    `90s`	DOUBLE,
    `Gls`	DOUBLE,
    `Ast`	DOUBLE,
    `G+A`	DOUBLE,
    `G-PK`	DOUBLE,
    `PK`	VARCHAR(512),
    `PKatt`	VARCHAR(512),
    `CrdY`	INT,
    `CrdR`	VARCHAR(512),
    `xG`	DOUBLE,
    `npxG`	DOUBLE,
    `xAG`	DOUBLE,
    `npxG+xAG`	DOUBLE,
    `PrgC`	INT,
    `PrgP`	INT,
    `PrgR`	INT,
    `Gls2`	DOUBLE,
    `Ast2`	DOUBLE,
    `G+A2`	DOUBLE,
    `G-PK2`	DOUBLE,
    `G+A-PK`	DOUBLE,
    `xG2`	DOUBLE,
    `xAG2`	DOUBLE,
    `xG+xAG`	DOUBLE,
    `npxG2`	DOUBLE,
    `npxG+xAG2`	DOUBLE,
    PRIMARY KEY (Rk)
);

DROP TABLE jugadores_pases;
CREATE TABLE `jugadores_pases` 
(
    `Rk`	INT,
    `Player`	VARCHAR(512),
    `Nation`	VARCHAR(512),
    `Pos`	VARCHAR(512),
    `Squad`	VARCHAR(512),
    `Age`	VARCHAR(512),
    `Born`	INT,
    `90s`	DOUBLE,
    `Cmp`	INT,
    `Att`	INT,
    `Cmp%`	DOUBLE,
    `TotDist`	INT,
    `PrgDist`	INT,
    `Cmp2`	INT,
    `Att2`	INT,
    `Cmp%2`	DOUBLE,
    `Cmp3`	INT,
    `Att3`	INT,
    `Cmp%3`	DOUBLE,
    `Cmp4`	INT,
    `Att4`	INT,
    `Cmp%4`	DOUBLE,
    `Ast`	VARCHAR(512),
    `xAG`	DOUBLE,
    `xA`	DOUBLE,
    `A-xAG`	DOUBLE,
    `KP`	VARCHAR(512),
    `1/3`	INT,
    `PPA`	VARCHAR(512),
    `CrsPA`	VARCHAR(512),
    `PrgP`	INT,
    PRIMARY KEY (Rk)
);

DROP TABLE jugadores_porteros_avanzado;
CREATE TABLE `jugadores_porteros_avanzado` 
(
    `Rk`	INT,
    `Player`	VARCHAR(512),
    `Nation`	VARCHAR(512),
    `Pos`	VARCHAR(512),
    `Squad`	VARCHAR(512),
    `Age`	VARCHAR(512),
    `Born`	INT,
    `90s`	DOUBLE,
    `GA`	INT,
    `PKA`	VARCHAR(512),
    `FK`	VARCHAR(512),
    `CK`	VARCHAR(512),
    `OG`	VARCHAR(512),
    `PSxG`	DOUBLE,
    `PSxG/SoT`	DOUBLE,
    `PSxG+/-`	DOUBLE,
    `/90`	DOUBLE,
    `Cmp`	INT,
    `Att`	INT,
    `Cmp%`	DOUBLE,
    `Att2`	INT,
    `Thr`	INT,
    `Launch%`	DOUBLE,
    `AvgLen`	DOUBLE,
    `Att3`	INT,
    `Launch%2`	DOUBLE,
    `AvgLen2`	DOUBLE,
    `Opp`	INT,
    `Stp`	INT,
    `Stp%`	DOUBLE,
    `#OPA`	INT,
    `#OPA/90`	DOUBLE,
    `AvgDist`	DOUBLE,
    PRIMARY KEY (Rk)
);

DROP TABLE jugadores_porteros;
CREATE TABLE `jugadores_porteros` 
(
    `Rk`	INT,
    `Player`	VARCHAR(512),
    `Nation`	VARCHAR(512),
    `Pos`	VARCHAR(512),
    `Squad`	VARCHAR(512),
    `Age`	VARCHAR(512),
    `Born`	INT,
    `MP`	INT,
    `Starts`	INT,
    `Min`	INT,
    `90s`	DOUBLE,
    `GA`	INT,
    `GA90`	DOUBLE,
    `SoTA`	INT,
    `Saves`	INT,
    `Save%`	VARCHAR(512),
    `W`	VARCHAR(512),
    `D`	VARCHAR(512),
    `L`	VARCHAR(512),
    `CS`	VARCHAR(512),
    `CS%`	DOUBLE,
    `PKatt`	VARCHAR(512),
    `PKA`	VARCHAR(512),
    `PKsv`	VARCHAR(512),
    `PKm`	VARCHAR(512),
    `Save%2`	VARCHAR(512),
    PRIMARY KEY (Rk)
);

DROP TABLE jugadores_posesion;
CREATE TABLE `jugadores_posesion` 
(
    `Rk`	INT,
    `Player`	VARCHAR(512),
    `Nation`	VARCHAR(512),
    `Pos`	VARCHAR(512),
    `Squad`	VARCHAR(512),
    `Age`	VARCHAR(512),
    `Born`	INT,
    `90s`	DOUBLE,
    `Touches`	INT,
    `Def Pen`	INT,
    `Def 3rd`	INT,
    `Mid 3rd`	INT,
    `Att 3rd`	INT,
    `Att Pen`	INT,
    `Live`	INT,
    `Att`	INT,
    `Succ`	VARCHAR(512),
    `Succ%`	DOUBLE,
    `Tkld`	VARCHAR(512),
    `Tkld%`	DOUBLE,
    `Carries`	INT,
    `TotDist`	INT,
    `PrgDist`	INT,
    `PrgC`	INT,
    `1/3`	INT,
    `CPA`	VARCHAR(512),
    `Mis`	INT,
    `Dis`	INT,
    `Rec`	INT,
    `PrgR`	INT,
    PRIMARY KEY (Rk)
);

DROP TABLE jugadores_tiempo_juego;
CREATE TABLE `jugadores_tiempo_juego` 
(
    `Rk`	INT,
    `Player`	VARCHAR(512),
    `Nation`	VARCHAR(512),
    `Pos`	VARCHAR(512),
    `Squad`	VARCHAR(512),
    `Age`	VARCHAR(512),
    `Born`	INT,
    `MP`	INT,
    `Min`	INT,
    `Mn/MP`	INT,
    `Min%`	DOUBLE,
    `90s`	DOUBLE,
    `Starts`	INT,
    `Mn/Start`	INT,
    `Compl`	VARCHAR(512),
    `Subs`	VARCHAR(512),
    `Mn/Sub`	VARCHAR(512),
    `unSub`	VARCHAR(512),
    `PPM`	DOUBLE,
    `onG`	VARCHAR(512),
    `onGA`	INT,
    `+/-`	INT,
    `+/-90`	DOUBLE,
    `On-Off`	DOUBLE,
    `onxG`	DOUBLE,
    `onxGA`	DOUBLE,
    `xG+/-`	DOUBLE,
    `xG+/-90`	DOUBLE,
    `On-Off2`	DOUBLE,
    PRIMARY KEY (Rk)
);

DROP TABLE jugadores_tipos_pases;
CREATE TABLE `jugadores_tipos_pases` 
(
    `Rk`	INT,
    `Player`	VARCHAR(512),
    `Nation`	VARCHAR(512),
    `Pos`	VARCHAR(512),
    `Squad`	VARCHAR(512),
    `Age`	VARCHAR(512),
    `Born`	INT,
    `90s`	DOUBLE,
    `Att`	INT,
    `Live`	INT,
    `Dead`	INT,
    `FK`	INT,
    `TB`	VARCHAR(512),
    `Sw`	INT,
    `Crs`	VARCHAR(512),
    `TI`	VARCHAR(512),
    `CK`	VARCHAR(512),
    `In`	VARCHAR(512),
    `Out`	VARCHAR(512),
    `Str`	VARCHAR(512),
    `Cmp`	INT,
    `Off`	VARCHAR(512),
    `Blocks`	INT,
    PRIMARY KEY (Rk)
);

DROP TABLE jugadores_tiros;
CREATE TABLE `jugadores_tiros` 
(
    `Rk`	INT,
    `Player`	VARCHAR(512),
    `Nation`	VARCHAR(512),
    `Pos`	VARCHAR(512),
    `Squad`	VARCHAR(512),
    `Age`	VARCHAR(512),
    `Born`	INT,
    `90s`	DOUBLE,
    `Gls`	VARCHAR(512),
    `Sh`	INT,
    `SoT`	VARCHAR(512),
    `SoT%`	DOUBLE,
    `Sh/90`	DOUBLE,
    `SoT/90`	DOUBLE,
    `G/Sh`	DOUBLE,
    `G/SoT`	DOUBLE,
    `Dist`	DOUBLE,
    `FK`	VARCHAR(512),
    `PK`	VARCHAR(512),
    `PKatt`	VARCHAR(512),
    `xG`	DOUBLE,
    `npxG`	DOUBLE,
    `npxG/Sh`	DOUBLE,
    `G-xG`	DOUBLE,
    `np:G-xG`	DOUBLE,
    PRIMARY KEY (Rk)
);